import { SectionHead } from '@/components/ui/Section';

const rounds = [
  {title:'OCTAVOS',matches:[['Martín Suárez','Diego Ramírez'],['Lucas Fernández','Tomás Gómez'],['Juan Pablo Ruiz','Matías Ortega'],['Federico Díaz','Santiago Morales'],['Nicolás Herrera','Agustín Torres'],['Ignacio Varela','Pablo Lemos'],['Matías Cabrera','Ezequiel Rojas'],['Andrés Medina','Bruno Castillo']]},
  {title:'CUARTOS',matches:[['Martín Suárez','Lucas Fernández'],['Juan Pablo Ruiz','Federico Díaz'],['Nicolás Herrera','Ignacio Varela'],['Matías Cabrera','Andrés Medina']]},
  {title:'SEMIFINALES',matches:[['Martín Suárez','Juan Pablo Ruiz'],['Nicolás Herrera','Andrés Medina']]},
  {title:'FINAL',matches:[['Martín Suárez','Nicolás Herrera']]}
];
export default async function TournamentPage({params}:{params:Promise<{id:string}>}){ await params; return <div className="page"><div className="tournament-head"><div className="tournament-icon">🎾</div><div><span className="tag">TENIS</span><h1>Torneo Apertura 2026</h1><p className="muted">1 de agosto – 15 de septiembre · Canchas de Tenis</p></div></div><div className="tabs"><span>Resumen</span><span className="active">Cuadro Principal</span><span>Resultados</span><span>Jugadores</span><span>Galería</span></div><section className="card"><SectionHead title="Cuadro Principal" action={<button className="btn btn-outline">↓ Descargar cuadro</button>}/><div className="bracket-wrap"><div className="bracket">{rounds.map((r,ri)=><div className="bracket-col" key={r.title}><h4>{r.title}</h4>{r.matches.map((m,i)=><div className="bracket-match" key={i}><b>✓ {m[0]} <span style={{float:'right'}}>6 6</span></b><span className="muted">{m[1]} <span style={{float:'right'}}>3 4</span></span></div>)}{ri===3&&<div style={{textAlign:'center',color:'#359f20',fontWeight:900,fontSize:18}}>🏆<br/>Campeón<br/>Martín Suárez</div>}</div>)}</div></div></section><section className="card" style={{marginTop:16,padding:'0 18px 18px'}}><SectionHead icon="▦" title="Detalles del Torneo"/><div className="admin-grid" style={{marginTop:0}}><div><p><b>Categoría</b><br/>Primera</p><p><b>Formato</b><br/>Eliminación directa</p></div><div><p><b>Superficie</b><br/>Polvo de ladrillo</p><p><b>Juez Árbitro</b><br/>Carlos Méndez</p></div></div></section></div> }
