import { notFound } from 'next/navigation';
import { TeamBadge } from '@/components/ui/TeamBadge';
import { SectionHead } from '@/components/ui/Section';
import { getMatches, getPlayers, getTeamBySlug, getTeams } from '@/lib/data';
import { formatDateTime } from '@/lib/format';

export default async function TeamPage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params; const team=await getTeamBySlug(slug); if(!team) notFound(); const [players,matches,teams]=await Promise.all([getPlayers(team.id),getMatches(team.sport_id),getTeams(team.sport_id)]); const lookup=(id?:string|null)=>teams.find(t=>t.id===id); const relevant=matches.filter(m=>m.home_team_id===team.id||m.away_team_id===team.id); const next=relevant.find(m=>m.status==='scheduled'); const recent=relevant.filter(m=>m.status==='finished').slice(0,5);
 return <div className="page"><section className="card team-hero"><TeamBadge team={team} size="lg"/><div className="team-info"><h1>{team.name}</h1><b className="muted">Categoría {team.category}</b><p>{team.description||'Equipo oficial del club.'}</p><p><b>Entrenador</b><br/>{team.coach_name||'Por asignar'}</p><div className="team-meta"><div>Fundación<b>{team.founded_year||'—'}</b></div><div>Colores<b>● ●</b></div><div>Sede<b>Club Deportivo</b></div></div></div>{next&&<div className="team-next"><SectionHead icon="🏆" title="Próximo Partido"/><p style={{textAlign:'center',color:'#359f20',fontWeight:800}}>{formatDateTime(next.scheduled_at)}</p><div className="fixture-teams"><div><TeamBadge team={lookup(next.home_team_id)}/><b style={{display:'block'}}>{lookup(next.home_team_id)?.name}</b></div><b>VS</b><div><TeamBadge team={lookup(next.away_team_id)}/><b style={{display:'block'}}>{lookup(next.away_team_id)?.name}</b></div></div></div>}</section>
 <div className="team-lower"><section className="card"><SectionHead icon="▤" title="Resultados recientes"/>{recent.map(m=><div className="result-row" style={{paddingLeft:16,paddingRight:16}} key={m.id}><small>{new Date(m.scheduled_at).toLocaleDateString('es-VE')}</small><div><b>{lookup(m.home_team_id)?.name} vs {lookup(m.away_team_id)?.name}</b></div><div className="result-score">{m.home_score}-{m.away_score}</div></div>)}</section><section className="card"><SectionHead icon="⚽" title="Estadísticas del Equipo"/><div className="stat-grid"><div className="stat-box"><b>12</b>Partidos</div><div className="stat-box"><b>8</b>Victorias</div><div className="stat-box"><b>2</b>Empates</div><div className="stat-box"><b>2</b>Derrotas</div><div className="stat-box"><b>28</b>Goles</div><div className="stat-box"><b>26</b>Puntos</div></div></section><section className="card"><SectionHead icon="▤" title="Plantilla"/><div className="table-wrap"><table className="data-table"><thead><tr><th>#</th><th>Jugador</th><th>POS</th><th>Edad</th><th>Estado</th></tr></thead><tbody>{players.map(p=><tr key={p.id}><td>{p.number}</td><td><b>{p.name}</b></td><td>{p.position}</td><td>{p.age}</td><td style={{color:'#359f20'}}>● {p.status}</td></tr>)}</tbody></table></div></section></div>
 <section className="card" style={{marginTop:16}}><SectionHead icon="▧" title="Galería del Equipo"/><div className="gallery-strip">{['1517466787929-bc90951d0974','1579952363873-27f3bade9f55','1552664730-d307ca884978','1508098682722-e99c43a406b2','1526232761682-d26e03ac148e'].map(id=><img key={id} src={`https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=500&q=80`} alt="Equipo"/>)}</div></section>
 </div>;
}
