'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';

type Option={id:string;name:string;sport_id?:string|null};
type MatchOption={id:string;label:string};
function useApi(){const [result,setResult]=useState('');const [loading,setLoading]=useState(false);const router=useRouter();async function call(url:string,payload:any){setLoading(true);setResult('');try{const res=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const data=await res.json();setResult(JSON.stringify(data,null,2));if(res.ok)router.refresh();return res.ok}finally{setLoading(false)}}return{call,result,loading}}

export function AdminForms({role,sports,leagues,matches}:{role:string;sports:Option[];leagues:Option[];matches:MatchOption[]}){
 const clubAdmin=['super_admin','club_admin'].includes(role); const sport=useApi(),news=useApi(),user=useApi(),stream=useApi(),team=useApi(),match=useApi();
 return <div className="admin-forms">
  {clubAdmin&&<form className="card admin-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await sport.call('/api/admin/sports',Object.fromEntries(f)))e.currentTarget.reset()}}><h3>＋ Crear deporte</h3><div className="field"><label>Nombre</label><input name="name" required placeholder="Ej. Hockey"/></div><div className="field"><label>Icono</label><input name="icon" placeholder="🏆"/></div><div className="field"><label>Descripción</label><textarea name="description"/></div><button className="btn btn-primary" disabled={sport.loading}>Crear deporte</button>{sport.result&&<pre className="api-result">{sport.result}</pre>}</form>}

  <form className="card admin-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await team.call('/api/admin/teams',Object.fromEntries(f)))e.currentTarget.reset()}}><h3>♧ Crear equipo</h3><div className="field"><label>Nombre</label><input name="name" required/></div><div className="field"><label>Deporte</label><select name="sport_id" required>{sports.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div className="field"><label>Liga</label><select name="league_id" required><option value="">Selecciona…</option>{leagues.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></div><div className="field"><label>Categoría</label><input name="category" placeholder="Primera / Sub-15"/></div><div className="field"><label>Entrenador</label><input name="coach_name"/></div><div className="field"><label>URL logo</label><input name="logo_url" placeholder="Puedes generarla en Multimedia"/></div><button className="btn btn-primary" disabled={team.loading}>Crear equipo</button>{team.result&&<pre className="api-result">{team.result}</pre>}</form>

  <form className="card admin-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await match.call('/api/admin/matches',Object.fromEntries(f)))e.currentTarget.reset()}}><h3>⚽ Actualizar resultado</h3><div className="field"><label>Partido</label><select name="id" required><option value="">Selecciona…</option>{matches.map(m=><option value={m.id} key={m.id}>{m.label}</option>)}</select></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><div className="field"><label>Local</label><input name="home_score" type="number" min="0"/></div><div className="field"><label>Visitante</label><input name="away_score" type="number" min="0"/></div></div><div className="field"><label>Estado</label><select name="status"><option value="live">En vivo</option><option value="finished">Finalizado</option><option value="scheduled">Programado</option><option value="postponed">Pospuesto</option></select></div><button className="btn btn-primary" disabled={match.loading}>Guardar marcador</button>{match.result&&<pre className="api-result">{match.result}</pre>}</form>

  <form className="card admin-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await news.call('/api/admin/news',Object.fromEntries(f)))e.currentTarget.reset()}}><h3>▣ Publicar noticia</h3><div className="field"><label>Título</label><input name="title" required/></div><div className="field"><label>Liga (opcional para admin; obligatoria para presidente)</label><select name="league_id"><option value="">General del club</option>{leagues.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></div><div className="field"><label>Categoría</label><select name="category"><option>Deportes</option><option>Eventos</option><option>Comunicados</option><option>Mantenimiento</option></select></div><div className="field"><label>Resumen</label><textarea name="excerpt"/></div><div className="field"><label>URL de imagen</label><input name="image_url" placeholder="Pega la URL de Multimedia"/></div><button className="btn btn-primary" disabled={news.loading}>Publicar noticia</button>{news.result&&<pre className="api-result">{news.result}</pre>}</form>

  {clubAdmin&&<form className="card admin-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await user.call('/api/admin/users',Object.fromEntries(f)))e.currentTarget.reset()}}><h3>♙ Crear usuario</h3><div className="field"><label>Nombre</label><input name="full_name" required/></div><div className="field"><label>Número de acción</label><input name="action_number" required/></div><div className="field"><label>Correo</label><input name="email" type="email" required/></div><div className="field"><label>Contraseña temporal</label><input name="password" type="password" minLength={8} required/></div><div className="field"><label>Rol</label><select name="role"><option value="member">Socio</option><option value="league_president">Presidente de liga</option><option value="editor">Editor</option><option value="manager">Gestor</option><option value="club_admin">Administrador</option></select></div><button className="btn btn-primary" disabled={user.loading}>Crear usuario</button>{user.result&&<pre className="api-result">{user.result}</pre>}</form>}

  <form className="card admin-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await stream.call('/api/admin/streams',Object.fromEntries(f))}}><h3>▶ Crear transmisión Mux</h3><div className="field"><label>Título</label><input name="title" required placeholder="Los Leones vs Atlético"/></div><div className="field"><label>Partido</label><select name="match_id"><option value="">Sin partido asociado</option>{matches.map(m=><option value={m.id} key={m.id}>{m.label}</option>)}</select></div><div className="field"><label>Latencia</label><select name="latency_mode"><option value="reduced">Reducida</option><option value="low">Baja</option><option value="standard">Estándar</option></select></div><button className="btn btn-primary" disabled={stream.loading}>Crear canal en vivo</button>{stream.result&&<><p className="muted" style={{fontSize:12}}>Copia Server y Stream Key a OBS. La Stream Key debe mantenerse privada.</p><pre className="api-result">{stream.result}</pre></>}</form>
 </div>
}
