import { notFound } from 'next/navigation';
import { requireSession } from '@/lib/auth';
import { getMatch, getMatchEvents, getMatchStats, getStream, getTeams } from '@/lib/data';
import { TeamBadge } from '@/components/ui/TeamBadge';
import { LivePlayer } from '@/components/live/LivePlayer';
import { LiveChat } from '@/components/live/LiveChat';
import { LiveEvents, LiveMatchScore } from '@/components/live/LiveRealtime';

export default async function LivePage({params}:{params:Promise<{id:string}>}){
 const {id}=await params; const [{profile,isDemo},stream]=await Promise.all([requireSession(),getStream(id)]); if(!stream)notFound(); const match=await getMatch(stream.match_id); if(!match)notFound(); const [teams,events,stats]=await Promise.all([getTeams(match.sport_id),getMatchEvents(match.id),getMatchStats(match.id)]);const home=teams.find(t=>t.id===match.home_team_id);const away=teams.find(t=>t.id===match.away_team_id);const rows=[['Posesión',stats.possession],['Tiros al Arco',stats.shots_on_target],['Tiros Totales',stats.shots],['Pases Completos',stats.passes],['Precisión de Pases',stats.accuracy],['Faltas',stats.fouls],['Corners',stats.corners]] as any[];
 return <div className="live-page"><div className="page"><div className="live-main"><section className="live-card"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h2 style={{margin:'0 0 12px'}}>Transmisión en Vivo</h2><span className="tag">EN VIVO</span></div><div className="player-wrap"><LivePlayer playbackId={stream.playback_id} title={stream.title} latencyMode={stream.latency_mode}/><span className="live-pill">● EN VIVO</span><div style={{position:'absolute',left:'50%',top:20,transform:'translateX(-50%)',display:'flex',alignItems:'center',gap:14}}><div style={{textAlign:'center'}}><TeamBadge team={home}/><small style={{display:'block'}}>{home?.name}</small></div><LiveMatchScore initialMatch={match} demo={isDemo}/><div style={{textAlign:'center'}}><TeamBadge team={away}/><small style={{display:'block'}}>{away?.name}</small></div></div></div></section><LiveChat streamId={stream.id} userId={profile.id} userName={profile.full_name} demo={isDemo}/></div><div className="live-grid"><LiveEvents matchId={match.id} initialEvents={events} demo={isDemo}/><section className="live-card live-panel"><h3>Estadísticas en Vivo</h3>{rows.map(([label,v])=>{const a=Number(v?.[0]??0),b=Number(v?.[1]??0),total=Math.max(1,a+b);return <div className="bar-row" key={label}><b>{a}{label.includes('Posesión')||label.includes('Precisión')?'%':''}</b><div className="bar"><i style={{width:`${a/total*100}%`}}/></div><span style={{textAlign:'center'}}>{label}</span><div className="bar"><i style={{width:`${b/total*100}%`}}/></div><b>{b}{label.includes('Posesión')||label.includes('Precisión')?'%':''}</b></div>})}</section><section className="live-card live-panel"><h3>Alineaciones</h3><div style={{height:300,borderRadius:12,background:'linear-gradient(#347a3b,#235f2d)',border:'2px solid rgba(255,255,255,.35)',position:'relative',overflow:'hidden'}}><div style={{position:'absolute',inset:'50% 0 auto',borderTop:'1px solid rgba(255,255,255,.45)'}}/><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:24,padding:32,textAlign:'center'}}>{['9 F. Ramírez','11 A. Morales','7 L. Torres','8 J. Vargas','10 R. Díaz','6 M. Ortega','3 P. Gómez','4 D. Silva','5 C. Rojas'].map(p=><span key={p} style={{background:'#06294a',border:'1px solid white',padding:7,borderRadius:999,fontSize:11}}>{p}</span>)}</div></div></section></div></div></div>
}
